/** shadcn CSS variables applied by the color theme picker (tweakcn-compatible).
 *  Shell surfaces (`shell-rail`, `shell-panel`) derive from `--sidebar` unless overridden.
 *  Border variants (`border-subtle`, `border`, `border-strong`) derive from raw `--border`. */

export type ThemeTokens = Partial<Record<string, string>>;

export type ColorThemePreset = {
  id: string;
  label: string;
  /** Primary swatch for the picker UI */
  swatch: string;
  light: ThemeTokens;
  dark: ThemeTokens;
};

export const NEUTRAL_THEME_ID = 'neutral';
export const DEFAULT_THEME_ID = 'notebook';

const tokens = (
  light: ThemeTokens,
  dark: ThemeTokens,
): Pick<ColorThemePreset, 'light' | 'dark'> => ({ light, dark });

/** Curated presets — values from https://github.com/jnsahaj/tweakcn */
export const COLOR_THEME_PRESETS: ColorThemePreset[] = [
  {
    id: NEUTRAL_THEME_ID,
    label: 'Playground',
    swatch: 'oklch(0.8422 0.1255 83.8529)',
    light: {},
    dark: {},
  },
  {
    id: 'amethyst-haze',
    label: 'Amethyst Haze',
    swatch: '#8a79ab',
    ...tokens(
      {
        background: '#f8f7fa',
        foreground: '#3d3c4f',
        card: '#ffffff',
        'card-foreground': '#3d3c4f',
        popover: '#ffffff',
        'popover-foreground': '#3d3c4f',
        primary: '#8a79ab',
        'primary-foreground': '#f8f7fa',
        secondary: '#dfd9ec',
        'secondary-foreground': '#3d3c4f',
        muted: '#dcd9e3',
        'muted-foreground': '#6b6880',
        accent: '#e6a5b8',
        'accent-foreground': '#4b2e36',
        destructive: '#d95c5c',
        border: '#cec9d9',
        input: '#eae7f0',
        ring: '#8a79ab',
        'chart-1': '#8a79ab',
        'chart-2': '#e6a5b8',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        radius: '0.5rem',
        sidebar: '#f1eff5',
        'sidebar-foreground': '#3d3c4f',
        'sidebar-primary': '#8a79ab',
        'sidebar-primary-foreground': '#f8f7fa',
        'sidebar-accent': '#e6a5b8',
        'sidebar-accent-foreground': '#4b2e36',
        'sidebar-border': '#d7d2e0',
        'sidebar-ring': '#8a79ab',
      },
      {
        background: '#1a1823',
        foreground: '#e0ddef',
        card: '#232030',
        'card-foreground': '#e0ddef',
        popover: '#232030',
        'popover-foreground': '#e0ddef',
        primary: '#a995c9',
        'primary-foreground': '#1a1823',
        secondary: '#5a5370',
        'secondary-foreground': '#e0ddef',
        muted: '#242031',
        'muted-foreground': '#a09aad',
        accent: '#372e3f',
        'accent-foreground': '#f2b8c6',
        destructive: '#e57373',
        border: '#302c40',
        input: '#2a273a',
        ring: '#a995c9',
        'chart-1': '#a995c9',
        'chart-2': '#f2b8c6',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        radius: '0.5rem',
        sidebar: '#16141e',
        'sidebar-foreground': '#e0ddef',
        'sidebar-primary': '#a995c9',
        'sidebar-primary-foreground': '#1a1823',
        'sidebar-accent': '#372e3f',
        'sidebar-accent-foreground': '#f2b8c6',
        'sidebar-border': '#2a273a',
        'sidebar-ring': '#a995c9',
      },
    ),
  },
  {
    id: 'violet-bloom',
    label: 'Violet Bloom',
    swatch: '#7033ff',
    ...tokens(
      {
        background: '#fdfdfd',
        foreground: '#000000',
        card: '#fdfdfd',
        'card-foreground': '#000000',
        popover: '#fcfcfc',
        'popover-foreground': '#000000',
        primary: '#7033ff',
        'primary-foreground': '#ffffff',
        secondary: '#edf0f4',
        'secondary-foreground': '#080808',
        muted: '#f5f5f5',
        'muted-foreground': '#525252',
        accent: '#e2ebff',
        'accent-foreground': '#1e69dc',
        destructive: '#e54b4f',
        border: '#e7e7ee',
        input: '#ebebeb',
        ring: '#000000',
        'chart-1': '#4ac885',
        'chart-2': '#7033ff',
        'chart-3': '#fd822b',
        'chart-4': '#3276e4',
        'chart-5': '#747474',
        radius: '1.4rem',
        sidebar: '#f5f8fb',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#000000',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ebebeb',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#000000',
      },
      {
        background: '#1a1b1e',
        foreground: '#f0f0f0',
        card: '#222327',
        'card-foreground': '#f0f0f0',
        popover: '#222327',
        'popover-foreground': '#f0f0f0',
        primary: '#8c5cff',
        'primary-foreground': '#ffffff',
        secondary: '#2a2c33',
        'secondary-foreground': '#f0f0f0',
        muted: '#2a2c33',
        'muted-foreground': '#a0a0a0',
        accent: '#1e293b',
        'accent-foreground': '#79c0ff',
        destructive: '#f87171',
        border: '#33353a',
        input: '#33353a',
        ring: '#8c5cff',
        'chart-1': '#4ade80',
        'chart-2': '#8c5cff',
        'chart-3': '#fca5a5',
        'chart-4': '#5993f4',
        'chart-5': '#a0a0a0',
        radius: '1.4rem',
        sidebar: '#161618',
        'sidebar-foreground': '#f0f0f0',
        'sidebar-primary': '#8c5cff',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a2c33',
        'sidebar-accent-foreground': '#8c5cff',
        'sidebar-border': '#33353a',
        'sidebar-ring': '#8c5cff',
      },
    ),
  },
  {
    id: 'modern-minimal',
    label: 'Modern Minimal',
    swatch: '#3b82f6',
    ...tokens(
      {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        radius: '0.375rem',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0f2fe',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
      },
      {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        'chart-1': '#60a5fa',
        'chart-2': '#3b82f6',
        'chart-3': '#2563eb',
        'chart-4': '#1d4ed8',
        'chart-5': '#1e40af',
        radius: '0.375rem',
        sidebar: '#171717',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1e3a8a',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#404040',
        'sidebar-ring': '#3b82f6',
      },
    ),
  },
  {
    id: 'notebook',
    label: 'Notebook',
    swatch: '#606060',
    ...tokens(
      {
        background: '#f9f9f9',
        foreground: '#3a3a3a',
        card: '#ffffff',
        'card-foreground': '#3a3a3a',
        popover: '#ffffff',
        'popover-foreground': '#3a3a3a',
        primary: '#606060',
        'primary-foreground': '#f0f0f0',
        secondary: '#dedede',
        'secondary-foreground': '#3a3a3a',
        muted: '#e3e3e3',
        'muted-foreground': '#505050',
        accent: '#f3eac8',
        'accent-foreground': '#5d4037',
        destructive: '#c87a7a',
        border: '#747272',
        input: '#ffffff',
        ring: '#a0a0a0',
        'chart-1': '#333333',
        'chart-2': '#555555',
        'chart-3': '#777777',
        'chart-4': '#999999',
        'chart-5': '#bbbbbb',
        radius: '0.625rem',
        sidebar: '#f0f0f0',
        'sidebar-foreground': '#3a3a3a',
        'sidebar-primary': '#606060',
        'sidebar-primary-foreground': '#f0f0f0',
        'sidebar-accent': '#f3eac8',
        'sidebar-accent-foreground': '#5d4037',
        'sidebar-border': '#c0c0c0',
        'sidebar-ring': '#a0a0a0',
      },
      {
        background: '#2b2b2b',
        foreground: '#dcdcdc',
        card: '#333333',
        'card-foreground': '#dcdcdc',
        popover: '#333333',
        'popover-foreground': '#dcdcdc',
        primary: '#b0b0b0',
        'primary-foreground': '#2b2b2b',
        secondary: '#5a5a5a',
        'secondary-foreground': '#c0c0c0',
        muted: '#454545',
        'muted-foreground': '#a0a0a0',
        accent: '#e0e0e0',
        'accent-foreground': '#333333',
        destructive: '#d9afaf',
        border: '#4f4f4f',
        input: '#333333',
        ring: '#c0c0c0',
        'chart-1': '#efefef',
        'chart-2': '#d0d0d0',
        'chart-3': '#b0b0b0',
        'chart-4': '#909090',
        'chart-5': '#707070',
        radius: '0.625rem',
        sidebar: '#212121',
        'sidebar-foreground': '#dcdcdc',
        'sidebar-primary': '#b0b0b0',
        'sidebar-primary-foreground': '#212121',
        'sidebar-accent': '#e0e0e0',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#4f4f4f',
        'sidebar-ring': '#c0c0c0',
      },
    ),
  },
];
